# Token Classes
T_PLUS = "ADD"
T_MINUS = "MINUS"
T_MUL = "MUL"
T_DIV = "DIV"
T_IDENTIFIER = "IDENTIFIER"
T_PHPOPEN = "PHPOPENTAG"
T_PHPCLOSE = "PHPCLOSETAG"
T_CLASS = "CLASS"
T_FUNCTION = "FUNCTION"
T_CURLYOPEN = "CURLYOPEN"
T_CURLYCLOSE = "CURLYCLOSE"
T_LITERAL = "STRING-LITERAL"
T_VAR = "VAR"
T_NUMBER = "NUMBER"
T_BOPEN = "BRACKETOPEN"
T_BCLOSE = "BRACKETCLOSE"
T_ECHO = "PRINT-OUTPUT"
T_ASSIGN = "ASSIGN"
T_EOL = "SEMICOLON"
T_CONCATE = "CONCATE"

# haven't been implemented yet
T_MULTIOPEN = "MULTIOPEN"
T_MULTICLOSE = "MULTICLOSE"

# IDENTIFIERS
IDENTIFIERS = ["class", "function", "echo"]